global:
  scrape_interval:     1s #

rule_files:
  - ./*.rules

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
     - targets:
        - "localhost:9090"
  - job_name: 'node'
    scrape_interval: 1s
    static_configs:
     - targets:
        - "localhost:9100"
